# Generated by Django 2.2 on 2020-12-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='musics/')),
                ('song_title', models.CharField(max_length=250)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
