# Generated by Django 2.2 on 2020-12-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='id_analisis',
            field=models.CharField(default='Vacio', max_length=250),
        ),
    ]
