# Generated by Django 2.2 on 2020-12-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_song_id_analisis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='musics/%Y/%m/$D/'),
        ),
    ]
