# Generated by Django 2.2 on 2020-12-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_auto_20201212_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='musics/%Y/%m/%D/'),
        ),
    ]
