# Generated by Django 2.2 on 2020-12-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0004_auto_20201212_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(default='Vacio', upload_to='musics/%Y/%m/%D/'),
        ),
    ]
